apiVersion: thinkube.io/v1
kind: ThinkubeDeployment
metadata:
  name: "{{ project_name }}"

spec:
  containers:
    - name: inference
      build: .
      port: 7860
      size: xlarge
      gpu:
        count: 1
        memory: "80Gi"  # Models loaded directly from MLflow S3 storage
      health: /health
      test:
        enabled: false  # Testing ML models requires GPU, skip in CI/CD

  routes:
    - path: /
      to: inference